Add support for all caps boolean values
ctavan/node-getenv pull request #22
Opened 2023-08-22 17:12 UTC by stephenlacy

Builds fail When running in XCode CI because the environment has `CI=TRUE`

2023-09-11 10:39 UTC, ctavan requested changes
Thank you for the contribution. Happy to accept it, but while we're at let, let's make it a bit more generic.

2023-09-11 10:39 UTC, ctavan commented on index.js
> +    return value === 'true' || value === 'TRUE';
See above, I'd prefer `return (value || '').toLowerCase() === 'true';`

2023-09-11 16:51 UTC, stephenlacy commented on index.js
> +    const isBool = value === 'true' || value === 'false' || value === 'TRUE' || value === 'FALSE';
Will update (I was aiming for the fewest number of changes)

2023-09-11 16:54 UTC, stephenlacy commented
Updated @ctavan

2023-09-12 07:28 UTC, ctavan approved these changes

2023-10-08 09:36 UTC, AndriiDemchenko commented on index.js
> +    return (value || '').toLowerCase() === 'true';
How about mapping?

```js
const BooleanMap = {
  true: true,
  TRUE: true,
  false: false,
  FALSE: false,
};

/**
 *
 * @param {string} value
 * @returns {boolean}
 */
function bool(value) {
  if (typeof value !== 'string') {
    throw new Error('Value is not a string');
  }

  const boolean = BooleanMap[value];

  // Or this one if you expect tRuE or similar
  // const boolean = BooleanMap[value.toLowerCase()];

  if (boolean === undefined) {
    throw new Error('Not a boolean');
  }

  return boolean;
}

console.log({
  value: bool('true'),
});
```

2024-12-25 18:38 UTC, brnhrdt commented
Is it possible to merge this and release a new version?

2024-12-25 19:42 UTC, stephenlacy commented
@ctavan Want to merge and cut a new release?

2024-12-28 20:30 UTC, nkat2112 commented
> @ctavan Want to merge and cut a new release?

@ctavan , @stephenlacy maybe please do not merge this pull request yet.

The change is very good. And it still won't work for the stack trace as demonstrated by @fdstevex in the following link:

https://github.com/expo/expo/issues/33486

Notice how the current fix is on the `bool: function(value)` function, when the stack trace shown here suggests it is (also) required in the `boolish: function(value)` method:

```
Error: GetEnv.NoBoolean: TRUE is not a boolean.
at Object.boolish (/Users/stevex/src/cloudmd/kiimobile/node_modules/getenv/index.js:70:15)
at /Users/stevex/src/cloudmd/kiimobile/node_modules/getenv/index.js:84:27
at Env.CI (/Users/stevex/src/cloudmd/kiimobile/node_modules/@expo/cli/src/utils/env.ts:40:19)
```

I too was running into this same issue.

I was able to get the build to Xcode Cloud to work only after patching the getenv module with an additional (and very similar) fix that @stephenlacy used - but in the boolish function.

Notice that the env.ts file indicated in the stack trace above calls boolish at that line number for 'CI', not bool.

I verified that the following fix, where I commented-out two lines and added the revised lines right after them, worked in the Xcode cloud:

```
  boolish: function(value) {
    try {
      return convert.bool(value);
    } catch (err) {

      // REPLACED: const isBool = value === '1' || value === '0';
      const isBool = (value || '').toLowerCase() === 'true' || (value || '').toLowerCase() === 'false' || value === '1' || value === '0';

      if (!isBool) {
        throw new Error('GetEnv.NoBoolean: ' + value + ' is not a boolean.');
      }

      // REPLACED: return value === '1';
      return (value || '').toLowerCase() === 'true' || value === '1';

    }
```

2024-12-28 21:22 UTC, stephenlacy commented
@nkat2112 `boolish` calls `bool` first, if that fails it continues with the numeral character check. https://github.com/ctavan/node-getenv/blob/5b02feebde5d8edd56fff7d81c4b43403a20aff8/index.js#L65
Can you confirm that your first patch actually was applied before adding the second patch? If the first fails for a different reason it would throw at `boolish`

2024-12-28 21:40 UTC, nkat2112 commented
@stephenlacy , I thought I did, but upon review, I messed up! Please ignore my comment and proceed with the pull request! I'm so sorry. Well done, by the way!

CC: @ctavan

2025-05-04 21:57 UTC, imrankhanpersonalai commented
Any idea when this can be merged?

2025-05-06 20:26 UTC, ctavan approved these changes

2025-05-06 20:27 UTC, merged

2025-05-06 21:13 UTC, ctavan commented
Released as `getenv@2.0.0`, thanks again and sorry for the wait!